name: ml_course
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - pip
  - lightgbm
  - matplotlib
  - scipy
  - numpy
  - pandas
  - requests
  - numexpr
  - bokeh
  - seaborn
  - pillow
  - ipywidgets
  - altair
  - bokeh
  - plotly
  - keras
  - pymc3
  - graphviz
  - python-graphviz
  - pydot
  - mkl-service
  - pycluster
  - statsmodels
  - jupyter_contrib_nbextensions
  - rise
  - spacy
  - pip:
    - corner
    - keract
    - tf-nightly-2.0-preview
    - umap-learn
    - URF
    - tsfresh
